const PackageData = [
    {
        packageId: "1",
        packageType: "document",
        packageWeight: "0.3 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Martin G.",
        senderAddress: "Lyulin",
        senderTelephone: "0000000001",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Ekaterina G.",
        recipientAddress: "Krasno selo",
        recipientTelephone: "093265623",
        processedBy: "Kristiqna Kruchmarava",
        deliveredByName: "Aleksandra",
        deliveredByPhone: "2345367890",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "2",
        packageType: "kolet",
        packageWeight: "3 kg",
        isFragile: true,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Krasno selo",
        senderName: "Ekaterina G.",
        senderAddress: "",
        senderTelephone: "2345678i9",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Marta G.",
        recipientAddress: "Mladost 5",
        recipientTelephone: "23456678",
        processedBy: "Krista Ssssssssss",
        deliveredByName: "Ico na Toni sukvartiranta",
        deliveredByPhone: "696969696969",
        shippingDate: "03.05.2021",
        deliveryDate: "06.05.2021",
        status: "in transit",
        comment: "Phone recepient before delivery."
    },
    {
        packageId: "3",
        packageType: "kolet",
        packageWeight: "1.25 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Marta G.",
        senderAddress: "Mlaost",
        senderTelephone: "0000000003",
        isShippedToOffice: true,
        shippedToOfficeName: "Burgas Cherno more",
        recipientName: "Preslava G.",
        recipientAddress: "",
        recipientTelephone: "0sdssdf",
        processedBy: "Anton Asenov",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "4",
        packageType: "palet",
        packageWeight: "5 kg",
        isFragile: false,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Lyulin",
        senderName: "Hristina N.",
        senderAddress: "",
        senderTelephone: "0000002401",
        isShippedToOffice: true,
        shippedToOfficeName: "Plovdiv Kapana",
        recipientName: "Martin G.",
        recipientAddress: "",
        recipientTelephone: "093345265623",
        processedBy: "Marta G.",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "30.04.2021",
        deliveryDate: "01.05.2021",
        status: "sorting",
        comment: "Please dont check order"
    },
    {
        packageId: "5",
        packageType: "document",
        packageWeight: "0.3 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Martin G.",
        senderAddress: "Lyulin",
        senderTelephone: "0000000001",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Ekaterina G.",
        recipientAddress: "Krasno selo",
        recipientTelephone: "093265623",
        processedBy: "Kristiqna Kruchmarava",
        deliveredByName: "Aleksandra",
        deliveredByPhone: "2345367890",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "6",
        packageType: "kolet",
        packageWeight: "3 kg",
        isFragile: true,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Krasno selo",
        senderName: "Ekaterina G.",
        senderAddress: "",
        senderTelephone: "2345678i9",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Marta G.",
        recipientAddress: "Mladost 5",
        recipientTelephone: "23456678",
        processedBy: "Krista Ssssssssss",
        deliveredByName: "Ico na Toni sukvartiranta",
        deliveredByPhone: "696969696969",
        shippingDate: "03.05.2021",
        deliveryDate: "06.05.2021",
        status: "in transit",
        comment: "Phone recepient before delivery."
    },
    {
        packageId: "7",
        packageType: "kolet",
        packageWeight: "1.25 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Marta G.",
        senderAddress: "Mlaost",
        senderTelephone: "0000000003",
        isShippedToOffice: true,
        shippedToOfficeName: "Burgas Cherno more",
        recipientName: "Preslava G.",
        recipientAddress: "",
        recipientTelephone: "0sdssdf",
        processedBy: "Anton Asenov",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "8",
        packageType: "palet",
        packageWeight: "5 kg",
        isFragile: false,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Lyulin",
        senderName: "Hristina N.",
        senderAddress: "",
        senderTelephone: "0000002401",
        isShippedToOffice: true,
        shippedToOfficeName: "Plovdiv Kapana",
        recipientName: "Martin G.",
        recipientAddress: "",
        recipientTelephone: "093345265623",
        processedBy: "Marta G.",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "30.04.2021",
        deliveryDate: "01.05.2021",
        status: "sorting",
        comment: "Please dont check order"
    },
    {
        packageId: "1",
        packageType: "document",
        packageWeight: "0.3 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Martin G.",
        senderAddress: "Lyulin",
        senderTelephone: "0000000001",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Ekaterina G.",
        recipientAddress: "Krasno selo",
        recipientTelephone: "093265623",
        processedBy: "Kristiqna Kruchmarava",
        deliveredByName: "Aleksandra",
        deliveredByPhone: "2345367890",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "2",
        packageType: "kolet",
        packageWeight: "3 kg",
        isFragile: true,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Krasno selo",
        senderName: "Ekaterina G.",
        senderAddress: "",
        senderTelephone: "2345678i9",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Marta G.",
        recipientAddress: "Mladost 5",
        recipientTelephone: "23456678",
        processedBy: "Krista Ssssssssss",
        deliveredByName: "Ico na Toni sukvartiranta",
        deliveredByPhone: "696969696969",
        shippingDate: "03.05.2021",
        deliveryDate: "06.05.2021",
        status: "in transit",
        comment: "Phone recepient before delivery."
    },
    {
        packageId: "3",
        packageType: "kolet",
        packageWeight: "1.25 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Marta G.",
        senderAddress: "Mlaost",
        senderTelephone: "0000000003",
        isShippedToOffice: true,
        shippedToOfficeName: "Burgas Cherno more",
        recipientName: "Preslava G.",
        recipientAddress: "",
        recipientTelephone: "0sdssdf",
        processedBy: "Anton Asenov",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "4",
        packageType: "palet",
        packageWeight: "5 kg",
        isFragile: false,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Lyulin",
        senderName: "Hristina N.",
        senderAddress: "",
        senderTelephone: "0000002401",
        isShippedToOffice: true,
        shippedToOfficeName: "Plovdiv Kapana",
        recipientName: "Martin G.",
        recipientAddress: "",
        recipientTelephone: "093345265623",
        processedBy: "Marta G.",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "30.04.2021",
        deliveryDate: "01.05.2021",
        status: "sorting",
        comment: "Please dont check order"
    },
    {
        packageId: "5",
        packageType: "document",
        packageWeight: "0.3 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Martin G.",
        senderAddress: "Lyulin",
        senderTelephone: "0000000001",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Ekaterina G.",
        recipientAddress: "Krasno selo",
        recipientTelephone: "093265623",
        processedBy: "Kristiqna Kruchmarava",
        deliveredByName: "Aleksandra",
        deliveredByPhone: "2345367890",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "6",
        packageType: "kolet",
        packageWeight: "3 kg",
        isFragile: true,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Krasno selo",
        senderName: "Ekaterina G.",
        senderAddress: "",
        senderTelephone: "2345678i9",
        isShippedToOffice: false,
        shippedToOfficeName: "",
        recipientName: "Marta G.",
        recipientAddress: "Mladost 5",
        recipientTelephone: "23456678",
        processedBy: "Krista Ssssssssss",
        deliveredByName: "Ico na Toni sukvartiranta",
        deliveredByPhone: "696969696969",
        shippingDate: "03.05.2021",
        deliveryDate: "06.05.2021",
        status: "in transit",
        comment: "Phone recepient before delivery."
    },
    {
        packageId: "7",
        packageType: "kolet",
        packageWeight: "1.25 kg",
        isFragile: false,
        isShippedFromOffice: false,
        shippedFromOfficeName: "",
        senderName: "Marta G.",
        senderAddress: "Mlaost",
        senderTelephone: "0000000003",
        isShippedToOffice: true,
        shippedToOfficeName: "Burgas Cherno more",
        recipientName: "Preslava G.",
        recipientAddress: "",
        recipientTelephone: "0sdssdf",
        processedBy: "Anton Asenov",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "07.04.2021",
        deliveryDate: "09.04.2021",
        status: "awaiting pick up",
        comment: ""
    },
    {
        packageId: "8",
        packageType: "palet",
        packageWeight: "5 kg",
        isFragile: false,
        isShippedFromOffice: true,
        shippedFromOfficeName: "Sofia Lyulin",
        senderName: "Hristina N.",
        senderAddress: "",
        senderTelephone: "0000002401",
        isShippedToOffice: true,
        shippedToOfficeName: "Plovdiv Kapana",
        recipientName: "Martin G.",
        recipientAddress: "",
        recipientTelephone: "093345265623",
        processedBy: "Marta G.",
        deliveredByName: "",
        deliveredByPhone: "",
        shippingDate: "30.04.2021",
        deliveryDate: "01.05.2021",
        status: "sorting",
        comment: "Please dont check order"
    }
]

export default PackageData;